# -*- coding: utf-8 -*-
"""F1_2026_Evolucion_Equipos_v4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dc1wvqFLWLp7lD5hn_47piR1oF53MRSP

## 1️⃣3️⃣ 📝 Resumen ejecutivo automático

La cereza del pastel: esta celda **lee todos los resultados anteriores y redacta las conclusiones sola**. Cada vez que re-ejecutes el notebook después de un GP, tendrás el resumen actualizado — listo para copiar a un post, un reporte o un mensaje al grupo de amigos que aún cree que los datos no sirven para la F1. 😏
"""

n_carreras = df["Ronda"].nunique()

# Líder de ritmo (menor déficit promedio)
ritmo = df.groupby("Equipo")["Deficit_pct"].mean().sort_values()
lider, def_lider = ritmo.index[0], ritmo.iloc[0]
segundo, def_segundo = ritmo.index[1], ritmo.iloc[1]

# Mejor y peor desarrollo con su credibilidad (R²)
conf = df_conf.set_index("Equipo")
mejor_dev = df_pend.iloc[0]
peor_dev = df_pend.iloc[-1]
r2_mejor = conf.loc[mejor_dev["Equipo"], "R2"] if mejor_dev["Equipo"] in conf.index else float("nan")
r2_peor = conf.loc[peor_dev["Equipo"], "R2"] if peor_dev["Equipo"] in conf.index else float("nan")

def credibilidad(r2):
    return "tendencia sólida" if r2 >= 0.5 else "tendencia aún ruidosa (tomar con pinzas)"

# Convergencia
tendencia_sigma = "se está APRETANDO 🤝" if b1_s < 0 else "se está ABRIENDO 🪂"

# Favoritos para la próxima
top3 = df_pred.head(3)

print("=" * 62)
print(f"🏁 RESUMEN EJECUTIVO — F1 {TEMPORADA} tras {n_carreras} carreras")
print("=" * 62)
print(f"""
1) RITMO: {lider} manda con {def_lider:.2f}% de déficit promedio;
   {segundo} es su perseguidor más cercano ({def_segundo:.2f}%).

2) DESARROLLO: {mejor_dev['Equipo']} es quien más recorta
   ({mejor_dev['Pendiente']:+.3f} %/carrera, R²={r2_mejor:.2f} → {credibilidad(r2_mejor)}).
   En el otro extremo, {peor_dev['Equipo']} se rezaga
   ({peor_dev['Pendiente']:+.3f} %/carrera, R²={r2_peor:.2f} → {credibilidad(r2_peor)}).

3) CONVERGENCIA: la parrilla {tendencia_sigma}
   ({b1_s:+.3f} puntos de σ por carrera).

4) PROYECCIÓN — Ronda {proxima_ronda} ({nombre_prox}):""")
for _, fila in top3.iterrows():
    print(f"   • {fila['Equipo']:<18} déficit proyectado {fila['Deficit_proyectado']:.3f}%")
print("""
⚠️ Proyección ingenua (tendencia pura, sin efecto circuito).
   Generado automáticamente — se actualiza al re-ejecutar el notebook.""")
print("=" * 62)

"""# 🏁 F1 2026 — Evolución de equipos con Déficit % al pole

**Objetivo:** medir cómo evoluciona el ritmo de cada equipo a lo largo de la temporada 2026, usando una métrica comparable entre circuitos:

$$\text{Déficit \%} = \frac{\text{Mejor tiempo del equipo} - \text{Tiempo pole}}{\text{Tiempo pole}} \times 100$$

**Por qué funciona:** el pole siempre vale 0%. Estar a 1.2% en Mónaco es comparable a estar a 1.2% en Monza, sin importar que una vuelta dure 70 s y la otra 100 s. Eso nos permite graficar toda la temporada en una sola línea por equipo.

**Escalabilidad:** el notebook detecta automáticamente cuántas carreras se han corrido. Después de cada GP solo vuelves a ejecutar todo (`Entorno de ejecución → Ejecutar todo`) y las gráficas se actualizan solas. 🔁 El caché vive en tu Google Drive, así que las carreras ya descargadas no se vuelven a bajar (y tu disco duro ni se entera 😉).

---
**Ruta del notebook:**
1. Instalación y configuración
2. Detectar carreras completadas de 2026
3. Extraer tiempos de qualy y calcular el Déficit %
4. 📈 Gráfica 1 — Evolución del déficit por equipo
5. 📉 Gráfica 2 — Pendiente de desarrollo (¿quién mejora más rápido?)
6. 🔮 Proyección ingenua para la siguiente carrera
7. Limitaciones y siguientes niveles

## 1️⃣ Instalación

Instalamos **FastF1**, la librería que descarga datos oficiales de tiempos de F1 (vueltas, resultados, telemetría). Plotly ya viene preinstalado en Colab.

> ⏱️ Tarda ~1 minuto. El `-q` es para que no llene la pantalla de logs.
"""

!pip install fastf1 -q
print("✅ FastF1 instalado")

"""## 2️⃣ Configuración (ahora con caché en tu Google Drive ☁️)

Tres cosas importantes aquí:
- **Caché persistente en Drive:** Colab borra su disco al cerrar la sesión, así que ahora el caché vive en `MyDrive/f1_cache`. La primera vez te pedirá autorizar el acceso a tu cuenta (un clic). A partir de ahí, cada re-ejecución solo descarga la carrera nueva. Si Drive no se puede montar, cae automáticamente a caché local para que el notebook nunca truene.
- **Logs silenciados de verdad:** FastF1 tiene varios loggers internos (`api`, `req`, `core`) y no todos obedecen al ajuste básico — por eso la salida se inundaba de `INFO:...`. Ahora los callamos a todos.
- **Renderer de Plotly** para que las gráficas interactivas se vean bien en Colab.
- **🎨 Tema oscuro + colores oficiales:** todas las gráficas usan `plotly_dark` y cada equipo lleva su color 2026 real. Los colores viven en el diccionario `COLORES_2026` — si algún tono no te convence, lo editas ahí una vez y todas las gráficas lo heredan.

> 💾 Peso estimado del caché de qualys: ~300-400 MB para la temporada completa de 22 rondas. Nada grave contra los 15 GB gratuitos de Drive.
"""

import fastf1
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
from pathlib import Path
import warnings, logging

warnings.filterwarnings("ignore")
pio.renderers.default = "colab"        # gráficas interactivas en Colab

# ---- 🎨 Tema oscuro global ----
pio.templates.default = "plotly_dark"

# ---- 🎨 Colores oficiales 2026 (edítalos a tu gusto aquí, un solo lugar) ----
COLORES_2026 = {
    "mercedes":   "#27F4D2",   # verde petronas
    "ferrari":    "#E80020",   # rosso corsa
    "mclaren":    "#FF8000",   # papaya
    "red bull":   "#3671C6",   # azul RBR (antes que "rb" para no confundir)
    "aston":      "#229971",   # verde british racing
    "alpine":     "#0093CC",   # azul alpine
    "williams":   "#64C4FF",   # azul claro
    "rb":         "#6692FF",   # racing bulls
    "haas":       "#B6BABD",   # gris/blanco
    "audi":       "#F50537",   # rojo audi sport
    "cadillac":   "#D4AF37",   # dorado cadillac
}

def obtener_color(equipo):
    """Empata el nombre del equipo (como venga en los datos) con su color por palabra clave."""
    e = equipo.lower()
    for clave, color in COLORES_2026.items():
        if clave in e:
            return color
    return "#888888"  # gris para equipos no mapeados


# ---- Silenciar TODOS los loggers de FastF1 (INFO/WARNING inundaban la salida) ----
def silenciar_fastf1():
    fastf1.logger.set_log_level("CRITICAL")
    for nombre in list(logging.root.manager.loggerDict):
        if "fastf1" in nombre:
            logging.getLogger(nombre).setLevel(logging.CRITICAL)
silenciar_fastf1()

# ---- Caché persistente en Google Drive (con respaldo local automático) ----
try:
    from google.colab import drive
    drive.mount("/content/drive")
    ruta_cache = "/content/drive/MyDrive/f1_cache"
except Exception:
    ruta_cache = "cache_f1"   # respaldo: caché local efímero (se borra al cerrar sesión)
    print("⚠️ No se pudo montar Drive — usando caché local temporal")

Path(ruta_cache).mkdir(parents=True, exist_ok=True)
fastf1.Cache.enable_cache(ruta_cache)

TEMPORADA = 2026
print(f"✅ Configuración lista — temporada {TEMPORADA}")
print(f"📦 Caché en: {ruta_cache}")

"""## 3️⃣ ¿Cuántas carreras llevamos?

Aquí está la clave de la **escalabilidad**: en vez de escribir a mano la lista de carreras, le pedimos a FastF1 el calendario completo de 2026 y filtramos las que ya ocurrieron. Cada vez que corras el notebook después de un GP, aparecerá una carrera más — sin tocar una línea de código.
"""

calendario = fastf1.get_event_schedule(TEMPORADA)

# Quitamos la pretemporada (tests)
calendario = calendario[calendario["EventFormat"] != "testing"].copy()

# Fecha de la carrera en UTC (con respaldo por si la columna viene vacía)
fecha_carrera = calendario["Session5DateUtc"].fillna(calendario["EventDate"])

ahora_utc = pd.Timestamp.utcnow().tz_localize(None)
completadas = calendario[fecha_carrera < ahora_utc].copy()

print(f"🏁 Carreras completadas hasta hoy: {len(completadas)} de {len(calendario)}\n")
print(completadas[["RoundNumber", "EventName", "Location"]].to_string(index=False))

"""## 4️⃣ Extraer tiempos de qualy y calcular el Déficit %

**¿Qué hace este bloque?** Para cada carrera completada:
1. Descarga la sesión de **qualy** (usamos qualy y no carrera porque en qualy todos van con poca gasolina y al límite → es la foto más limpia del potencial del auto).
2. Toma el mejor tiempo de cada piloto (el mínimo entre Q1, Q2 y Q3).
3. Se queda con **el mejor piloto de cada equipo** → así aislamos el auto y minimizamos el ruido del piloto que tuvo mala vuelta.
4. Calcula el Déficit % contra el pole.

> ⏱️ La primera ejecución tarda unos segundos por carrera (descarga datos). Las siguientes son casi instantáneas gracias al caché.
"""

silenciar_fastf1()   # FastF1 crea loggers nuevos al vuelo; los volvemos a callar

registros = []
colores_equipo = {}

for _, ev in completadas.iterrows():
    ronda = int(ev["RoundNumber"])
    nombre_gp = ev["EventName"]
    try:
        q = fastf1.get_session(TEMPORADA, ronda, "Q")
        q.load(laps=True, telemetry=False, weather=False, messages=False)

        res = q.results
        if res is None or len(res) == 0:
            raise ValueError("Sin resultados de qualy")

        # Mejor tiempo por piloto = mínimo entre Q1, Q2, Q3
        tmp = res[["TeamName", "Q1", "Q2", "Q3"]].copy()
        tmp["MejorVuelta"] = tmp[["Q1", "Q2", "Q3"]].min(axis=1)
        tmp = tmp.dropna(subset=["MejorVuelta"])

        # Mejor piloto de cada equipo
        por_equipo = tmp.groupby("TeamName")["MejorVuelta"].min()
        pole = por_equipo.min()

        for equipo, tiempo in por_equipo.items():
            deficit = (tiempo - pole) / pole * 100
            registros.append({
                "Ronda": ronda,
                "GranPremio": nombre_gp.replace(" Grand Prix", ""),
                "Equipo": equipo,
                "MejorVuelta_s": round(tiempo.total_seconds(), 3),
                "Deficit_pct": round(deficit, 3),
            })
            # Color oficial del equipo (si la versión de FastF1 lo soporta)
            if equipo not in colores_equipo:
                colores_equipo[equipo] = obtener_color(equipo)

        print(f"✅ Ronda {ronda:>2} — {nombre_gp}")
    except Exception as e:
        print(f"⚠️ Ronda {ronda:>2} — {nombre_gp}: no se pudo cargar ({e})")

df = pd.DataFrame(registros)
print(f"\n📊 Dataset listo: {len(df)} filas ({df['Equipo'].nunique()} equipos, {df['Ronda'].nunique()} carreras)")
df.head(12)

"""### 🧭 Cómo leer este dataset

Cada fila es un **equipo en una carrera**. Es formato *tidy* (largo), el ideal para Plotly y para modelos:

| Columna | Significado |
|---|---|
| `Ronda` | Número de carrera en el calendario (nuestro eje del tiempo) |
| `Deficit_pct` | Distancia al pole en %. **0 = hizo la pole. Menor = mejor.** |

💾 Guardamos también un CSV por si quieres llevártelo a Power Query o Power BI:
"""

df.to_csv(f"deficit_f1_{TEMPORADA}.csv", index=False)
print(f"💾 Guardado: deficit_f1_{TEMPORADA}.csv (panel izquierdo → 📁 Archivos)")

"""## 5️⃣ 📈 Gráfica 1 — Evolución del déficit por equipo

**La gráfica principal del proyecto.** Cada línea es un equipo; el eje X es la ronda y el eje Y su déficit % contra el pole.

### 🧭 Guía de lectura
- **Línea que baja** 📉 = el equipo se acerca al ritmo de referencia → sus mejoras funcionan.
- **Línea que sube** 📈 = se está quedando atrás (o los demás mejoran más rápido — el déficit es *relativo*).
- **Picos aislados** = normalmente son efecto circuito (una pista que no le sienta al auto) o una qualy con lluvia/incidentes. No te cases con un solo punto: busca la **tendencia**.
- **Interactividad:** haz clic en la leyenda para ocultar equipos, doble clic para aislar uno, y arrastra sobre la gráfica para hacer zoom.
"""

# Ordenamos leyenda por déficit promedio (los más rápidos arriba)
orden_equipos = df.groupby("Equipo")["Deficit_pct"].mean().sort_values().index.tolist()

mapa_colores = {e: c for e, c in colores_equipo.items() if c}

fig1 = px.line(
    df.sort_values("Ronda"),
    x="Ronda", y="Deficit_pct",
    color="Equipo",
    markers=True,
    category_orders={"Equipo": orden_equipos},
    color_discrete_map=mapa_colores,
    hover_data={"GranPremio": True, "MejorVuelta_s": True, "Deficit_pct": ":.2f"},
    title=f"Déficit % al pole por equipo — Temporada {TEMPORADA}",
    labels={"Deficit_pct": "Déficit vs. pole (%)", "Ronda": "Ronda del calendario"},
)
fig1.update_layout(
    hovermode="x unified",
    legend_title_text="Equipo (clic para ocultar)",
    template="plotly_dark",
    height=550,
)
fig1.update_xaxes(dtick=1)
fig1.show()

"""### 🤔 Preguntas para practicar tu lectura
1. ¿Qué equipo tiene la línea más **plana y cercana a 0**? Ese es el auto de referencia de la temporada.
2. ¿Ves algún equipo con un **pico raro** en una sola carrera? Busca qué pasó ese fin de semana (lluvia, bandera roja, pista atípica).
3. ¿Hay algún equipo cuya línea **cruza** a otra? Ese cruce es un cambio de jerarquía — el momento exacto en que un desarrollo rindió frutos.

## 6️⃣ 📉 Gráfica 2 — Pendiente de desarrollo

Aquí convertimos la intuición de "este equipo está mejorando" en **un número**: ajustamos una regresión lineal por equipo

$$\text{Déficit}_i = \beta_0 + \beta_1 \cdot \text{Ronda}_i + \varepsilon_i$$

y nos quedamos con la pendiente $\beta_1$:

- $\beta_1 < 0$ → el déficit **baja** con el tiempo = **el equipo está desarrollando bien** 💪
- $\beta_1 > 0$ → el déficit **sube** = se está rezagando
- $\beta_1 \approx 0$ → estancado (o ya es el referente y no tiene a dónde bajar)

La unidad es *puntos porcentuales de déficit por carrera*. Ej.: −0.05 significa que recorta ~0.05% al pole en cada GP.
"""

pendientes = []
for equipo, g in df.groupby("Equipo"):
    if g["Ronda"].nunique() >= 3:  # mínimo 3 puntos para una tendencia digna
        b1, b0 = np.polyfit(g["Ronda"], g["Deficit_pct"], 1)
        pendientes.append({"Equipo": equipo, "Pendiente": b1, "Intercepto": b0,
                           "Carreras": g["Ronda"].nunique()})

df_pend = pd.DataFrame(pendientes).sort_values("Pendiente")

fig2 = px.bar(
    df_pend,
    x="Pendiente", y="Equipo",
    orientation="h",
    color="Pendiente",
    color_continuous_scale=["#1D9E75", "#D3D1C7", "#E24B4A"],
    title="Pendiente de desarrollo (β₁): negativo = mejora, positivo = se rezaga",
    labels={"Pendiente": "Cambio en déficit % por carrera"},
    hover_data={"Carreras": True, "Pendiente": ":.4f"},
)
fig2.add_vline(x=0, line_dash="dash", line_color="#AAAAAA")
fig2.update_layout(template="plotly_dark", height=450, coloraxis_showscale=False)
fig2.show()

"""### 🧭 Guía de lectura
- Las barras **verdes hacia la izquierda** son los equipos que más recortan por carrera.
- **Ojo con la trampa estadística:** con pocas carreras, una pendiente puede estar dominada por 1-2 fines de semana atípicos. Entre más avance la temporada, más confiable se vuelve. Esto se llama *sensibilidad al tamaño de muestra* y es exactamente lo que los modelos jerárquicos (nivel 2 del proyecto) corrigen.

### 📈 Bonus: las tendencias sobre los datos

La misma regresión, pero visual — puntos reales + línea de tendencia por equipo (OLS de Plotly):
"""

fig3 = px.scatter(
    df, x="Ronda", y="Deficit_pct",
    color="Equipo",
    trendline="ols",
    category_orders={"Equipo": orden_equipos},
    color_discrete_map=mapa_colores,
    title="Déficit % con línea de tendencia por equipo",
    labels={"Deficit_pct": "Déficit vs. pole (%)", "Ronda": "Ronda"},
)
fig3.update_layout(template="plotly_dark", height=550,
                   legend_title_text="Equipo (doble clic para aislar)")
fig3.update_xaxes(dtick=1)
fig3.show()

"""## 7️⃣ 🔮 Proyección ingenua para la siguiente carrera

Con la recta de cada equipo podemos **extrapolar** su déficit esperado en la próxima ronda:

$$\widehat{\text{Déficit}}_{\text{próx}} = \beta_0 + \beta_1 \cdot \text{Ronda}_{\text{próx}}$$

⚠️ **Se llama "ingenua" a propósito:** asume que la tendencia continúa y que el circuito no importa. Es el *baseline* contra el que compararás modelos más sofisticados (efecto circuito, efectos mixtos). Si tu modelo avanzado no le gana a esta recta, no vale la pena la complejidad — lección clave de ciencia de datos. 😉
"""

proxima_ronda = int(df["Ronda"].max()) + 1

prox_evento = calendario[calendario["RoundNumber"] == proxima_ronda]
nombre_prox = prox_evento["EventName"].iloc[0] if len(prox_evento) else "fin de temporada 🏁"

df_pred = df_pend.copy()
df_pred["Deficit_proyectado"] = (df_pred["Intercepto"]
                                 + df_pred["Pendiente"] * proxima_ronda).round(3)
# El déficit no puede ser negativo: lo acotamos en 0 (sería "más rápido que el pole")
df_pred["Deficit_proyectado"] = df_pred["Deficit_proyectado"].clip(lower=0)
df_pred = df_pred.sort_values("Deficit_proyectado")

print(f"🔮 Proyección para la ronda {proxima_ronda}: {nombre_prox}\n")
print(df_pred[["Equipo", "Deficit_proyectado", "Pendiente", "Carreras"]]
      .to_string(index=False))

fig4 = px.bar(
    df_pred, x="Deficit_proyectado", y="Equipo", orientation="h",
    color="Equipo", color_discrete_map=mapa_colores,
    title=f"Déficit % proyectado — Ronda {proxima_ronda} ({nombre_prox})",
    labels={"Deficit_proyectado": "Déficit proyectado vs. pole (%)"},
)
fig4.update_layout(template="plotly_dark", height=450, showlegend=False,
                   yaxis={"categoryorder": "total descending"})
fig4.show()

"""---
# 🔬 Profundizando: 4 análisis que los datos nos están pidiendo

Al leer los resultados saltan tres cosas:
1. **Mercedes está anclado en 0** — hizo la pole en todas las carreras, así que su déficit es 0 *por construcción* y no podemos ver su evolución.
2. Algunas pendientes podrían estar **infladas por circuitos atípicos** (Mónaco no se parece a nada).
3. Con reglamento nuevo, la teoría dice que la parrilla **converge** — pero aún no lo medimos.

Las siguientes secciones atacan exactamente eso. 👇

## 9️⃣ Des-anclando a Mercedes: déficit contra la mediana del campo

**El problema:** medir contra el pole tiene dos defectos. (a) El equipo que hace la pole queda clavado en 0 y desaparece su evolución. (b) El pole es **un solo dato** — si Verstappen se saca una vuelta marciana, el déficit de *todos* se infla artificialmente esa carrera.

**La solución:** cambiar la referencia al **centro del campo**:

$$\text{Déficit}_{med}\% = \frac{\text{Tiempo equipo} - \text{Mediana del campo}}{\text{Mediana del campo}} \times 100$$

Usamos la **mediana** y no el promedio porque es robusta: un Cadillac a 5% no la mueve.

### 🧭 Cómo cambia la lectura
- Ahora los valores **negativos** existen: significan "más rápido que el equipo típico".
- **Mercedes por fin tiene línea con forma** — si baja, se está escapando del pelotón; si sube, el pelotón lo está alcanzando *aunque siga haciendo poles*. Eso era invisible antes. 👀
"""

# Mediana del campo por carrera y nuevo déficit
mediana_ronda = df.groupby("Ronda")["MejorVuelta_s"].transform("median")
df["Deficit_med_pct"] = ((df["MejorVuelta_s"] - mediana_ronda) / mediana_ronda * 100).round(3)

fig5 = px.line(
    df.sort_values("Ronda"),
    x="Ronda", y="Deficit_med_pct",
    color="Equipo", markers=True,
    category_orders={"Equipo": orden_equipos},
    color_discrete_map=mapa_colores,
    hover_data={"GranPremio": True, "Deficit_med_pct": ":.2f"},
    title="Déficit % contra la MEDIANA del campo — negativo = más rápido que el equipo típico",
    labels={"Deficit_med_pct": "Déficit vs. mediana (%)", "Ronda": "Ronda"},
)
fig5.add_hline(y=0, line_dash="dash", line_color="#AAAAAA",
               annotation_text="Mediana del campo")
fig5.update_layout(hovermode="x unified", template="plotly_dark", height=550,
                   legend_title_text="Equipo (clic para ocultar)")
fig5.update_xaxes(dtick=1)
fig5.show()

# ¿Y la pendiente de Mercedes que antes era invisible?
merc = df[df["Equipo"] == "Mercedes"]
if len(merc) >= 3:
    b1_merc, _ = np.polyfit(merc["Ronda"], merc["Deficit_med_pct"], 1)
    direccion = "se ESCAPA del pelotón 🚀" if b1_merc < 0 else "el pelotón lo está ALCANZANDO 🎯"
    print(f"Pendiente de Mercedes vs. mediana: {b1_merc:+.4f} % por carrera → {direccion}")

"""### 🤔 Pregunta clave
Compara esta gráfica con la Gráfica 1. Los equipos que "mejoraban" contra el pole, ¿también mejoran contra la mediana? Si un equipo recorta contra el pole pero no contra la mediana, lo que en realidad pasó es que **Mercedes bajó su ritmo** — no que ese equipo mejorara. Esta es la diferencia entre una referencia de un punto y una referencia del campo completo.

## 🔟 La convergencia de la parrilla, medida en un número

Con reglamento nuevo los de atrás copian soluciones de los de adelante, y la física pone un techo: cada década de segundo cuesta más que el anterior. Resultado teórico: **la dispersión del campo debería encogerse** carrera tras carrera.

Lo medimos con la desviación estándar del déficit en cada ronda:

$$\sigma_r = \sqrt{\frac{1}{N-1}\sum_{e=1}^{N}\left(\text{Déficit}_{e,r} - \overline{\text{Déficit}}_r\right)^2}$$

### 🧭 Guía de lectura
- **σ bajando** = la parrilla se aprieta (convergencia). Cada décima de desarrollo te mueve más posiciones — la clasificación se vuelve una lotería de centésimas.
- **σ subiendo** = alguien encontró algo grande y se escapa.
- La línea punteada es la tendencia lineal de σ: su pendiente es **la velocidad de convergencia de la temporada**, un solo número que resume la era reglamentaria. 🤌
"""

dispersion = (df.groupby(["Ronda", "GranPremio"])["Deficit_pct"]
                .std().reset_index(name="Sigma"))

b1_s, b0_s = np.polyfit(dispersion["Ronda"], dispersion["Sigma"], 1)
dispersion["Tendencia"] = b0_s + b1_s * dispersion["Ronda"]

fig6 = go.Figure()
fig6.add_trace(go.Scatter(
    x=dispersion["Ronda"], y=dispersion["Sigma"],
    mode="lines+markers", name="σ del déficit",
    customdata=dispersion["GranPremio"],
    hovertemplate="Ronda %{x} (%{customdata})<br>σ = %{y:.3f}%<extra></extra>",
))
fig6.add_trace(go.Scatter(
    x=dispersion["Ronda"], y=dispersion["Tendencia"],
    mode="lines", name=f"Tendencia ({b1_s:+.3f}%/carrera)",
    line=dict(dash="dash"),
))
fig6.update_layout(
    title="Convergencia de la parrilla: dispersión (σ) del déficit por carrera",
    xaxis_title="Ronda", yaxis_title="σ del déficit (%)",
    template="plotly_dark", height=450,
)
fig6.update_xaxes(dtick=1)
fig6.show()

veredicto = "CONVERGE 🤝 (la parrilla se aprieta)" if b1_s < 0 else "DIVERGE 🪂 (alguien se escapa)"
print(f"Velocidad de convergencia: {b1_s:+.4f} puntos de σ por carrera → la parrilla {veredicto}")

"""## 1️⃣1️⃣ 🗺️ La huella de circuito: ¿qué pista le sienta a cada auto?

Aquí atacamos la sospecha de los "picos aislados". Para cada equipo separamos su nivel general de su comportamiento en cada pista:

$$\text{Residuo}_{e,r} = \text{Déficit}_{e,r} - \overline{\text{Déficit}}_e$$

Es decir: *¿ese fin de semana el equipo estuvo mejor o peor que **su propio promedio**?*

### 🧭 Guía de lectura del mapa de calor
- 🔵 **Azul** = el equipo rindió **mejor que su normal** en esa pista.
- 🔴 **Rojo** = rindió **peor que su normal**.
- **Columnas mayormente rojas o azules** = qualy atípica que afectó a varios (lluvia, banderas) — ruido de sesión, no efecto circuito.
- **Celdas aisladas intensas** = eso sí es huella de circuito: el auto tiene una debilidad/fortaleza específica (baja carga, curvas lentas, bumps).

Esta matriz es la semilla del **nivel 2**: si agrupas las columnas por tipo de pista y los patrones se repiten, ya tienes tu efecto circuito para el modelo de efectos mixtos.
"""

# Matriz equipo × carrera de residuos (déficit relativo al promedio propio)
pivote = df.pivot_table(index="Equipo", columns="Ronda", values="Deficit_pct")
residuos = pivote.sub(pivote.mean(axis=1), axis=0)

# Etiquetas de columnas con nombre de GP y filas ordenadas por ritmo
nombres_gp = df.drop_duplicates("Ronda").set_index("Ronda")["GranPremio"]
residuos.columns = [f"R{r} {nombres_gp.get(r, '')}" for r in residuos.columns]
residuos = residuos.reindex(orden_equipos)

fig7 = px.imshow(
    residuos,
    color_continuous_scale="RdBu_r",
    color_continuous_midpoint=0,
    aspect="auto",
    title="Huella de circuito: residuo vs. el promedio propio (azul = mejor que su normal)",
    labels=dict(color="Residuo (%)"),
    text_auto=".2f",
)
fig7.update_layout(template="plotly_dark", height=500,
                   xaxis_title="", yaxis_title="")
fig7.show()

"""### 🤔 Preguntas para practicar
1. Localiza **Mónaco**. ¿Qué equipos tienen su celda más azul ahí? Esos autos tienen buena carga aerodinámica/tracción en lentas.
2. ¿Hay alguna **columna completa** teñida? Investiga qué pasó en esa qualy antes de sacar conclusiones del auto.
3. ¿La celda más roja de Haas o Aston Martin coincide con las carreras que inflaban su pendiente positiva? Si sí, su "empeoramiento" es en parte efecto circuito — argumento directo para el nivel 2.

## 1️⃣2️⃣ ⚖️ ¿A qué pendientes creerles? Señal vs. ruido

Última pieza: dos equipos pueden tener la misma pendiente, pero uno con puntos pegaditos a la recta y otro con puntos regados. La confianza no es la misma. La medimos con el **coeficiente de determinación**:

$$R^2 = 1 - \frac{\sum_i (y_i - \hat{y}_i)^2}{\sum_i (y_i - \bar{y})^2}$$

- $R^2 \to 1$: la tendencia explica casi todo → **pendiente creíble**.
- $R^2 \to 0$: los puntos son ruido alrededor de la recta → la pendiente puede ser espejismo de 1-2 carreras.

### 🧭 Cómo leer el mapa de cuadrantes
| Cuadrante | Significado |
|---|---|
| ⬅️⬆️ Pendiente negativa + R² alto | **Desarrollo real y sostenido** — creíble 💎 |
| ⬅️⬇️ Pendiente negativa + R² bajo | Mejora, pero errática — espera más datos 🤨 |
| ➡️⬆️ Pendiente positiva + R² alto | **Declive consistente** — foco rojo confirmado 🚨 |
| ➡️⬇️ Pendiente positiva + R² bajo | Probablemente ruido/efecto circuito 🎲 |
"""

filas = []
for equipo, g in df.groupby("Equipo"):
    if g["Ronda"].nunique() >= 3:
        b1, b0 = np.polyfit(g["Ronda"], g["Deficit_pct"], 1)
        y_hat = b0 + b1 * g["Ronda"]
        ss_res = ((g["Deficit_pct"] - y_hat) ** 2).sum()
        ss_tot = ((g["Deficit_pct"] - g["Deficit_pct"].mean()) ** 2).sum()
        r2 = 1 - ss_res / ss_tot if ss_tot > 0 else 0.0
        filas.append({"Equipo": equipo, "Pendiente": round(b1, 4), "R2": round(max(r2, 0), 3)})

df_conf = pd.DataFrame(filas)

fig8 = px.scatter(
    df_conf, x="Pendiente", y="R2",
    text="Equipo", color="Equipo",
    color_discrete_map=mapa_colores,
    title="Mapa de credibilidad: pendiente de desarrollo vs. R²",
    labels={"Pendiente": "Pendiente (β₁) — negativo = mejora", "R2": "R² del ajuste"},
)
fig8.add_vline(x=0, line_dash="dash", line_color="#AAAAAA")
fig8.add_hline(y=0.5, line_dash="dot", line_color="#AAAAAA",
               annotation_text="Umbral de credibilidad (referencial)")
fig8.update_traces(textposition="top center", marker_size=12)
fig8.update_layout(template="plotly_dark", height=550, showlegend=False)
fig8.show()

print(df_conf.sort_values("Pendiente").to_string(index=False))

"""### 💡 El insight que junta todo

Cruza este mapa con la huella de circuito: si un equipo tiene R² bajo **y** sus peores residuos caen en pistas de un mismo tipo, ya no es misterio — es un auto sensible al tipo de circuito. Formalizar eso es exactamente el **modelo de efectos mixtos** del nivel 2:

$$\text{Déficit}_{e,r} = \beta_{0e} + \beta_{1e}\cdot\text{Ronda}_r + \gamma\cdot\text{TipoCircuito}_r + \varepsilon_{e,r}$$

donde cada equipo tiene su propio intercepto y pendiente ($\beta_{0e}, \beta_{1e}$) y $\gamma$ captura el efecto del tipo de pista. Todo lo que construimos en estas 4 secciones son los ingredientes de ese modelo. 🧑‍🍳

### 🧭 Guía de lectura
El equipo con la barra **más corta** es el favorito según la tendencia pura. Cuando pase la carrera real, vuelve a correr el notebook y compara: ¿la proyección le atinó al orden? Ese error de predicción es tu primera métrica de evaluación (puedes registrar el **MAE** carrera a carrera — ejercicio propuesto 😏).

---

## 8️⃣ Limitaciones y siguientes niveles

Lo que este MVP **no** captura todavía (y por eso hay niveles 2 y 3):

1. **Efecto circuito** 🏟️ — un auto con mucha carga aerodinámica brilla en Mónaco y sufre en Monza. *Siguiente paso:* agrupar circuitos por características (velocidad media, % de curvas lentas) y agregarlo al modelo.
2. **Incertidumbre** 🎲 — la recta te da un número, no un rango. *Siguiente paso:* modelo de efectos mixtos (`statsmodels.mixedlm`) o bayesiano (PyMC) para decir "probabilidad de que X esté delante de Y".
3. **Ritmo de carrera vs. qualy** ⛽ — la qualy mide potencial a una vuelta; la carrera mide degradación de llantas y gestión. *Siguiente paso:* repetir el análisis con stints de carrera filtrados (`laps.pick_quicklaps()`).
4. **Mejoras discretas** 🔧 — los upgrades llegan en paquetes, no de forma lineal. *Siguiente paso:* detección de puntos de cambio (*changepoint detection*).

---

## 📚 Referencias

- Gelman, A., & Hill, J. (2007). *Data analysis using regression and multilevel/hierarchical models*. Cambridge University Press.
- Schaefer, P., & colaboradores de FastF1. (2026). *FastF1 documentation*. https://docs.fastf1.dev
- Plotly Technologies Inc. (2026). *Plotly Python graphing library*. https://plotly.com/python/

---
*Notebook generado como MVP del proyecto de análisis longitudinal F1 2026. Para actualizarlo después de cada GP: `Entorno de ejecución → Ejecutar todo`.* 🏎️💨
"""